# Generated by Django 5.1 on 2025-01-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="total_page",
            field=models.IntegerField(default=330),
            preserve_default=False,
        ),
    ]
