# Generated by Django 5.1.7 on 2025-03-27 22:13

import bookshelf.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_book_total_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfile',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=bookshelf.models.handle_file_upload, validators=[bookshelf.models.file_validation]),
        ),
    ]
